Add a test to demonstrate problems deleting refs
The failure looks like this:

  could not delete branch-1
  To /var/folders/5x/mpy0zsy11vq8m3pgs0mcz_yw0000gn/T/remote1636666213
   ! [remote rejected] branch-1 (missing necessary objects)
  error: failed to push some refs to '/var/folders/5x/mpy0zsy11vq8m3pgs0mcz_yw0000gn/T/remote1636666213'